spring.application.name=PrefPet
#server.port=8081

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.username=backend
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://database.local.prefpet.com.br:3306/PrefPet?useSSL=true&requireSSL=true&trustCertificateKeyStoreUrl=classpath:client_truststore.jks&trustCertificateKeyStorePassword=${JKS_PASSWORD}&fallbackToSystemTrustStore=false

#spring.datasource.url=jdbc:mysql://localhost:3306/PrefPet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://back.local.prefpet.com.br:8444/realms/prefpet


keycloak.server-url=https://back.local.prefpet.com.br:8444

keycloak.realm=prefpet

keycloak.client-id=admin-cli

keycloak.username=admin
keycloak.password=admin